version: '3.8'

services:
  # Banco de Dados PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: agents-chat-postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${LOBE_DB_NAME}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - agents-chat

  # Redis para cache
  redis:
    image: redis:7-alpine
    container_name: agents-chat-redis
    restart: unless-stopped
    volumes:
      - ./data/redis:/data
    networks:
      - agents-chat

  # MinIO para armazenamento de arquivos
  minio:
    image: minio/minio:latest
    container_name: agents-chat-minio
    restart: unless-stopped
    ports:
      - "${MINIO_PORT:-9000}:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    volumes:
      - ./data/minio:/data
    networks:
      - agents-chat

  # Casdoor para autenticação
  casdoor:
    image: casbin/casdoor:latest
    container_name: agents-chat-casdoor
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - httpport=8000
      - RUNNING_IN_DOCKER=true
      - driverName=postgres
      - dataSourceName=user=postgres password=${POSTGRES_PASSWORD} host=postgres port=5432 sslmode=disable dbname=casdoor
      - runmode=prod
      - logConfig_console=true
      - logConfig_file=true
      - logConfig_level=Info
    volumes:
      - ./data/casdoor:/app/conf
    depends_on:
      - postgres
    networks:
      - agents-chat

  # Aplicação principal
  app:
    image: agents-chat:latest
    container_name: agents-chat-app
    restart: unless-stopped
    ports:
      - "${LOBE_PORT:-3210}:3210"
    environment:
      # Fix para erros de CSP (Three.js)
      - NEXT_PUBLIC_CSP_DISABLED=true
      # Banco de Dados
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/${LOBE_DB_NAME}
      - DATABASE_DRIVER=node
      # Redis
      - REDIS_URL=redis://redis:6379
      # MinIO/S3
      - S3_ENDPOINT=http://minio:9000
      - S3_ACCESS_KEY_ID=${MINIO_ROOT_USER:-minioadmin}
      - S3_SECRET_ACCESS_KEY=${MINIO_ROOT_PASSWORD}
      - S3_BUCKET=${MINIO_LOBE_BUCKET}
      - S3_PUBLIC_DOMAIN=${S3_PUBLIC_DOMAIN:-${NEXT_PUBLIC_SITE_URL}:9000}
      - NEXT_PUBLIC_S3_DOMAIN=${NEXT_PUBLIC_S3_DOMAIN:-${NEXT_PUBLIC_SITE_URL}:9000}
      # Autenticação Casdoor
      - AUTH_CASDOOR_ISSUER=${AUTH_CASDOOR_ISSUER}
      - AUTH_CASDOOR_ID=${AUTH_CASDOOR_ID}
      - AUTH_CASDOOR_SECRET=${AUTH_CASDOOR_SECRET}
      - AUTH_CASDOOR_ENDPOINT=http://casdoor:8000
      - AUTH_CASDOOR_PUBLIC_ENDPOINT=${AUTH_CASDOOR_ISSUER}
      - NEXT_AUTH_SSO_PROVIDERS=casdoor
      - NEXTAUTH_URL=${NEXT_PUBLIC_SITE_URL}
      # Aplicação
      - APP_URL=${NEXT_PUBLIC_SITE_URL}
      - NEXT_PUBLIC_SITE_URL=${NEXT_PUBLIC_SITE_URL}
      - NEXT_PUBLIC_SERVICE_MODE=server
      - NEXT_PUBLIC_ENABLE_NEXT_AUTH=1
      - HOSTNAME=0.0.0.0
      - PORT=3210
      - NODE_ENV=production
      - NODE_OPTIONS=--max-old-space-size=2048
      # Segurança
      - NEXT_AUTH_SECRET=${NEXT_AUTH_SECRET}
      - KEY_VAULTS_SECRET=${KEY_VAULTS_SECRET}
      # API Keys
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - AZURE_API_KEY=${AZURE_API_KEY}
      - AZURE_ENDPOINT=${AZURE_ENDPOINT}
      - AZURE_API_VERSION=${AZURE_API_VERSION}
      # Configurações opcionais
      - ACCESS_CODE=${ACCESS_CODE}
      - FEATURE_FLAGS=${FEATURE_FLAGS}
      - DEBUG=${DEBUG}
    depends_on:
      - postgres
      - redis
      - minio
      - casdoor
    networks:
      - agents-chat
    volumes:
      - ./logs/app:/app/logs

networks:
  agents-chat:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  minio_data:
